[package]
name = "randyx"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "randyx"
path =  "os/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort" 

[dependencies]
bootloader = "0.9.8"
